--------------------------------------------------------
-- Archivo creado  - viernes-marzo-11-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBLTIENDA
--------------------------------------------------------

  CREATE TABLE "TIENDA"."TBLTIENDA" 
   (	"TIENNIT" NUMBER(*,0), 
	"TIENNOMBRE" VARCHAR2(50 BYTE), 
	"TIENFECHACREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBLELECTRODOMESTICO
--------------------------------------------------------

  CREATE TABLE "TIENDA"."TBLELECTRODOMESTICO" 
   (	"ELECTSERIAL" NUMBER(*,0), 
	"ELECTTIPO" VARCHAR2(20 BYTE), 
	"ELECTMARCA" VARCHAR2(40 BYTE), 
	"ELECTPAISORIGEN" VARCHAR2(40 BYTE), 
	"ELECTANIOFABRICACION" NUMBER(*,0), 
	"TIENNIT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TIENDA.TBLTIENDA
SET DEFINE OFF;
Insert into TIENDA.TBLTIENDA (TIENNIT,TIENNOMBRE,TIENFECHACREACION) values ('1061819','Ktronix',to_date('10/03/22','DD/MM/RR'));
Insert into TIENDA.TBLTIENDA (TIENNIT,TIENNOMBRE,TIENFECHACREACION) values ('1061919','Alkosto',to_date('03/02/22','DD/MM/RR'));
Insert into TIENDA.TBLTIENDA (TIENNIT,TIENNOMBRE,TIENFECHACREACION) values ('1061877','Exito',to_date('07/05/21','DD/MM/RR'));
Insert into TIENDA.TBLTIENDA (TIENNIT,TIENNOMBRE,TIENFECHACREACION) values ('1061807','Jumbo',to_date('30/07/15','DD/MM/RR'));
REM INSERTING into TIENDA.TBLELECTRODOMESTICO
SET DEFINE OFF;
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1010','Televisor','LG','China','2019','1061819');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1111','Nevera','Whirlpool','EE.UU','2020','1061877');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1212','Televisor','Alcatel','Colombia','2022','1061819');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1313','Lavadora','LG','EE.UU','2018','1061877');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1414','Lavadora','Kaley','Colombia','2022','1061807');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1515','Televisor','Xiaomi','China','2015','1061919');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1616','Televisor','Samsung','Japón','2022','1061919');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1717','Nevera','Xiaomi','China','2016','1061807');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1818','Nevera','Kaley','Colombia','2020','1061807');
Insert into TIENDA.TBLELECTRODOMESTICO (ELECTSERIAL,ELECTTIPO,ELECTMARCA,ELECTPAISORIGEN,ELECTANIOFABRICACION,TIENNIT) values ('1919','Lavadora','Samsung','Brasil','2018','1061877');
--------------------------------------------------------
--  DDL for Index PK_TBLTIENDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIENDA"."PK_TBLTIENDA" ON "TIENDA"."TBLTIENDA" ("TIENNIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TBLELECTRODOMESTICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIENDA"."PK_TBLELECTRODOMESTICO" ON "TIENDA"."TBLELECTRODOMESTICO" ("ELECTSERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TBLTIENDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIENDA"."PK_TBLTIENDA" ON "TIENDA"."TBLTIENDA" ("TIENNIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TBLELECTRODOMESTICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIENDA"."PK_TBLELECTRODOMESTICO" ON "TIENDA"."TBLELECTRODOMESTICO" ("ELECTSERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBLTIENDA
--------------------------------------------------------

  ALTER TABLE "TIENDA"."TBLTIENDA" MODIFY ("TIENNIT" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLTIENDA" MODIFY ("TIENNOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLTIENDA" MODIFY ("TIENFECHACREACION" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLTIENDA" ADD CONSTRAINT "CKC_TIENNIT" CHECK (tienNit > 0) ENABLE;
  ALTER TABLE "TIENDA"."TBLTIENDA" ADD CONSTRAINT "PK_TBLTIENDA" PRIMARY KEY ("TIENNIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLELECTRODOMESTICO
--------------------------------------------------------

  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" MODIFY ("ELECTSERIAL" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" MODIFY ("ELECTTIPO" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" MODIFY ("ELECTMARCA" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" MODIFY ("ELECTPAISORIGEN" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" MODIFY ("ELECTANIOFABRICACION" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" MODIFY ("TIENNIT" NOT NULL ENABLE);
  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" ADD CONSTRAINT "CKC_ELECTSERIAL" CHECK (electSerial > 0) ENABLE;
  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" ADD CONSTRAINT "CKC_ELECTTIPO" CHECK (electTipo in ('Televisor', 'Lavadora', 'Nevera')) ENABLE;
  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" ADD CONSTRAINT "PK_TBLELECTRODOMESTICO" PRIMARY KEY ("ELECTSERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBLELECTRODOMESTICO
--------------------------------------------------------

  ALTER TABLE "TIENDA"."TBLELECTRODOMESTICO" ADD CONSTRAINT "FK_TIENELECT" FOREIGN KEY ("TIENNIT")
	  REFERENCES "TIENDA"."TBLTIENDA" ("TIENNIT") ENABLE;
